### ISSUE TITLE
"num_samples should be a positive integer value" error when training detection model

### ISSUE THREAD

**Issue by Phaired** [robertknight/ocrs-models#27] opened 2024-08-11 23:03 UTC
Hi, I attempted to train a model using my own datasets by following the provided guide, but encountered an error during the process. Below are the details of the commands executed and the error message received.

### Steps to Reproduce

1. Navigate to the project directory:
   ```shell
   PS C:\Users\phaired\ocrs-models>
   ```

2. Install project dependencies using Poetry:
   ```shell
   poetry install
   ```

   Output:
   ```shell
   Installing dependencies from lock file

   No dependencies to install or update

   Installing the current project: ocrs-models (0.1.0)
   ```

3. Ensure PyTorch and TorchVision are installed:
   ```shell
   poetry run pip install torch torchvision
   ```

   Output:
   ```shell
   Requirement already satisfied: torch in c:\users\phaired\appdata\local\pypoetry\cache\virtualenvs\ocrs-models-lkqg8ybo-py3.11\lib\site-packages (2.4.0)
   Requirement already satisfied: torchvision in c:\users\phaired\appdata\local\pypoetry\cache\virtualenvs\ocrs-models-lkqg8ybo-py3.11\lib\site-packages (0.19.0)
   Requirement already satisfied: filelock in c:\users\phaired\appdata\local\pypoetry\cache\virtualenvs\ocrs-models-lkqg8ybo-py3.11\lib\site-packages (from torch) (3.15.4)
   Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\phaired\appdata\local\pypoetry\cache\virtualenvs\ocrs-models-lkqg8ybo-py3.11\lib\site-packages (from torch) (4.9.0)
   Requirement already satisfied: sympy in c:\users\phaired\appdata\local\pypoetry\cache\virtualenvs\ocrs-models-lkqg8ybo-py3.11\lib\site-packages (from torch) (1.13.2)
   Requirement already satisfied: networkx in c:\users\phaired\appdata\local\pypoetry\cache\virtualenvs\ocrs-models-lkqg8ybo-py3.11\lib\site-packages (from torch) (3.3)
   Requirement already satisfied: jinja2 in c:\users\phaired\appdata\local\pypoetry\cache\virtualenvs\ocrs-models-lkqg8ybo-py3.11\lib\site-packages (from torch) (3.1.4)
   Requirement already satisfied: fsspec in c:\users\phaired\appdata\local\pypoetry\cache\virtualenvs\ocrs-models-lkqg8ybo-py3.11\lib\site-packages (from torch) (2024.6.1)
   Requirement already satisfied: numpy<2 in c:\users\phaired\appdata\local\pypoetry\cache\virtualenvs\ocrs-models-lkqg8ybo-py3.11\lib\site-packages (from torchvision) (1.26.3)
   Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\phaired\appdata\local\pypoetry\cache\virtualenvs\ocrs-models-lkqg8ybo-py3.11\lib\site-packages (from torchvision) (10.3.0)
   Requirement already satisfied: MarkupSafe>=2.0 in c:\users\phaired\appdata\local\pypoetry\cache\virtualenvs\ocrs-models-lkqg8ybo-py3.11\lib\site-packages (from jinja2->torch) (2.1.5)
   Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\phaired\appdata\local\pypoetry\cache\virtualenvs\ocrs-models-lkqg8ybo-py3.11\lib\site-packages (from sympy->torch) (1.3.0)
   ```

4. Run the training script:
   ```shell
   poetry run python -m ocrs_models.train_detection hiertext datasets/hiertext/ --max-images 100
   ```

### Error Message

Upon running the training script, the following error was encountered:

```plaintext
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\phaired\ocrs-models\ocrs_models\train_detection.py", line 489, in <module>
    main()
  File "C:\Users\phaired\ocrs-models\ocrs_models\train_detection.py", line 350, in main
    train_dataloader = DataLoader(
                       ^^^^^^^^^^^
  File "C:\Users\phaired\AppData\Local\pypoetry\Cache\virtualenvs\ocrs-models-LkQG8YbO-py3.11\Lib\site-packages\torch\utils\data\dataloader.py", line 351, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phaired\AppData\Local\pypoetry\Cache\virtualenvs\ocrs-models-LkQG8YbO-py3.11\Lib\site-packages\torch\utils\data\sampler.py", line 144, in __init__
    raise ValueError(f"num_samples should be a positive integer value, but got num_samples={self.num_samples}")
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

### Directory Listing

Below is the listing of the `hiertext` dataset directory:

```plaintext
    Directory: C:\Users\phaired\ocrs-models\datasets\hiertext

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        12/08/2024     00:35                docs
d-----        12/08/2024     00:35                evaluator
d-----        12/08/2024     00:40                gt
d-----        03/03/2022     12:40                test
d-----        03/03/2022     12:40                train
d-----        03/03/2022     12:40                validation
-a----        12/08/2024     00:35          13123 eval.py
-a----        12/08/2024     00:35        1331813 HierText_Visualization.ipynb
-a----        12/08/2024     00:35          20566 LICENSE
-a----        12/08/2024     00:35          11902 README.md
-a----        12/08/2024     00:35            115 requirements.txt
-a----        12/08/2024     00:35            572 sample_eval_scores.txt
-a----        12/08/2024     00:35       20357682 sample_output.jsonl.gz
-a----        03/03/2022     13:17      537066598 test.tgz
-a----        03/03/2022     13:18     2798458845 train.tgz
-a----        03/03/2022     13:22      577088394 validation.tgz
```

### Additional Information

- The datasets are correctly placed in the respective directories (`train`, `test`, `validation`).
- The error suggests that `num_samples` is 0, indicating that the dataset may not be loading properly.

I would appreciate any guidance on resolving this issue.

EDIT: I obviously downloaded and extracted the image into train/test/validation directories...

**Comment by robertknight** [comment] 2024-08-12 07:48
Can you check the contents of `datasets/hiertext/gt/`. It contains several `.jsonl.gz` files which should be decompressed to `.jsonl` files when training is run for the first time. After running the detection training script, the `train.jsonl` file should be generated:

```
$ ls -lh datasets/hiertext/gt/
total 797496
-rw-r--r--  1 robert  staff    32M 30 Jan  2024 train-lines.jsonl
-rw-r--r--  1 robert  staff   234M  4 Jan  2024 train.jsonl
-rw-r--r--  1 robert  staff    56M  4 Jan  2024 train.jsonl.gz
-rw-r--r--  1 robert  staff   6.5M 30 Jan  2024 validation-lines.jsonl
-rw-r--r--  1 robert  staff    49M  4 Jan  2024 validation.jsonl
-rw-r--r--  1 robert  staff    12M  4 Jan  2024 validation.jsonl.gz
```

Can you check if the `train.jsonl` and `validation.jsonl` files are present and whether their size matches the above values.

The code that loads the dataset is the [`HierText` class](https://github.com/robertknight/ocrs-models/blob/03ef651b4ab7126e1a7b7114ba408e575f69bbb3/ocrs_models/datasets/hiertext.py#L22). The error message suggests that the `_annotations` field in the `HierText` class is an empty list, whereas it should be an array with one entry per line in `train.jsonl`:

```
 $ wc -l datasets/hiertext/gt/train.jsonl
    8281 datasets/hiertext/gt/train.jsonl
```

One thing I will note here is that I haven't tried running training on Windows before, so it is possible there are some cross platform issues which need to be resolved.

**Comment by Phaired** [comment] 2024-08-12 09:03
I am experiencing a crash when trying to decompress a `.jsonl.gz` file while training a model using the HierText dataset. The error occurs immediately after the JSON file is being converted to the JSONL format. Here are the details of the command executed and the error message received.


 ```plaintext
poetry run python -m ocrs_models.train_detection hiertext datasets/hiertext --max-images 100
Converting annotations from JSON to JSONL format...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\phaired\ocrs-models\ocrs_models\train_detection.py", line 490, in <module>
    main()
  File "C:\Users\phaired\ocrs-models\ocrs_models\train_detection.py", line 348, in main
    train_dataset = load_dataset(
                    ^^^^^^^^^^^^^
  File "C:\Users\phaired\ocrs-models\ocrs_models\datasets\hiertext.py", line 53, in __init__
    self._generate_json_lines_annotations(annotations_file, lines_file)
  File "C:\Users\phaired\ocrs-models\ocrs_models\datasets\hiertext.py", line 128, in _generate_json_lines_annotations
    for ann in tqdm(annotations):
               ^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
```

### Diagnostic Information

- When checking the number of lines in the decompressed JSONL file, it appears to be empty:

  ```shell
  wc -l datasets/hiertext/gt/train.jsonl
  0 datasets/hiertext/gt/train.jsonl
  ```

- This may explain the problem, as the dataset file seems to contain no data.

### Environment

- The issue was tested on both Windows and WSL, with the same problem occurring on both platforms.

**Comment by robertknight** [comment] 2024-08-12 09:33
Ah, I see. A bug was introduced in some refactoring I did a while back. I missed this as I already had decompressed files cached locally. This has been fixed in https://github.com/robertknight/ocrs-models/pull/28.

To resolve the issue:

1. Update to the latest git commit for this repo
2. Remove any empty files in `datasets/hiertextt/gt`.
3. Re-run the command to start training

Let me know if the problem is not resolved.

**Comment by Phaired** [comment] 2024-08-12 10:30
Thank you for the quick response in resolving my previous issue. I have an additional, unrelated question regarding model training.



How many images are typically needed to train a model effectively when the images are of a very specific type, where only the text changes and all other features remain constant?


- **Image Consistency**: The images used for training are highly consistent, with only variations in the text content. All other features such as layout, style, and background remain unchanged.
- **Objective**: The goal is to train a model to accurately recognize or process the text within these images, given the uniformity in other aspects.



I would appreciate any insights or recommendations on the approximate number of images needed for such a training scenario. If there are any best practices or guidelines you could suggest for dataset preparation in this context, it would be greatly helpful.

Thank you for your guidance.

If this is not the appropriate place to discuss this question, please feel free to close the issue. Thank you for your support :)

**Comment by robertknight** [comment] 2024-08-13 21:26
> How many images are typically needed to train a model effectively when the images are of a very specific type, where only the text changes and all other features remain constant?

It depends if you are starting from scratch or using an existing checkpoint. If you start from an existing checkpoint (aka. fine tuning), which you can find on [Hugging Face](https://huggingface.co/robertknight/ocrs), this should reduce the number of images needed significantly.

It's hard to estimate exactly how much data will be required but, as a data point, in some experiments with synthetic text line images a while back I was able to get character error rates of a little under 1% with 5000 text lines ([experiment link](https://wandb.ai/robertknight/text-recognition/runs/gx2mz7om/overview)). This was training from scratch though.

**Closed** 2024-08-13 21:27 UTC
